import numpy as np
import pandas as pd
from typing import List

class ProbabilityOfBacktestOverfitting:
    @staticmethod
    def calculate_from_cpcv(metrics_matrix: np.ndarray) -> float:
        """
        Calculates PBO using the matrix of performance metrics generated by CPCV.
        metrics_matrix: shape (num_paths, num_strategies)
        Each element is the performance (e.g., Sharpe) of a strategy on a specific simulated path.
        """
        num_paths, num_strategies = metrics_matrix.shape
        
        if num_paths <= 1 or num_strategies <= 1:
            return 0.0 # Cannot overfit a single strategy or evaluate on a single path
            
        logits = []
        
        # In CPCV, paths are naturally split into Train (IS) and Test (OOS) pairs.
        # Assuming the matrix represents the IS metrics. We need the corresponding OOS matrix.
        # For simplicity in this interface, we assume metrics_matrix is the paired IS/OOS tuples,
        # but normally CPCV generates paths S. 
        # We will implement the core ranking logic here.
        raise NotImplementedError("PBO calculate_from_cpcv requires paired IS/OOS paths. Use calculate_cscv directly.")

    @staticmethod
    def calculate_cscv(is_metrics: np.ndarray, oos_metrics: np.ndarray) -> float:
        """
        Combinatorially Symmetric Cross Validation (CSCV) PBO calculation.
        is_metrics: shape (num_splits, num_strategies) - In-Sample performance
        oos_metrics: shape (num_splits, num_strategies) - Out-of-Sample performance
        
        Returns the Probability of Backtest Overfitting (PBO), which is the probability
        that the strategy performing best In-Sample performs below the median Out-of-Sample.
        """
        num_splits, num_strategies = is_metrics.shape
        
        if num_splits == 0 or num_strategies <= 1:
            return 0.0
            
        relative_ranks = []
        
        for i in range(num_splits):
            # 1. Identify the optimal strategy In-Sample
            best_is_idx = np.argmax(is_metrics[i, :])
            
            # 2. Rank all strategies Out-of-Sample
            oos_row = oos_metrics[i, :]
            # Sort OOS performances
            sorted_oos = np.sort(oos_row)
            
            # 3. Find the relative rank of the IS-optimal strategy in the OOS set
            best_is_oos_perf = oos_row[best_is_idx]
            # Calculate percentile rank (0 to 1)
            rank_pct = np.sum(sorted_oos < best_is_oos_perf) / float(num_strategies - 1)
            relative_ranks.append(rank_pct)
            
        # PBO is the probability that the optimal IS strategy ranks below the median (0.5) OOS
        relative_ranks = np.array(relative_ranks)
        pbo = np.sum(relative_ranks < 0.5) / float(num_splits)
        
        return pbo
